### ISSUE TITLE
Job-Order-Tracking-System/app/controllers/job_orders_controller.rb

### ISSUE THREAD

**Issue by jultra** [UPTAC-KomSai/Job-Order-Tracking-System#1]
Hello, 

Do refactor the code in your controller files. For example, do use Rail's built-in support for data validation [validation](http://guides.rubyonrails.org/active_record_validations.html) as discussed in class.

**Comment by Beeyeah** [comment]
yes sir

**Comment by jhamezzz1315** [comment]
Sir kitaa nala please an refractor na branch kung amo na po ba tim gusto sir.

**Comment by Beeyeah** [comment]
Sir pwede pacheck utro han job_order controller?

pati liwat sir an pagpartial ha _request_form tapos _nav nga ada ha shared folder para han views?

**Comment by jultra** [comment]
The code looks a lot lot better now Beeyeah! 👍 Good job! Suggestion: why not ig.alias nyo an routes ha iyo, using :as keyword ha definition ha config.ru. Para inside your views or controller actions, magamit nyo an url helper pgdisplay han paths/urls:

E.g.,

`get '/job_orders/list_pending_requests' => 'job_orders#list_pending_requests', :as => 'pending_jo'`

Then inside your controller method:

say ha create_job_order:

```
def create
    ....
    #should put notice here
    redirect_to pending_jo_path
end
```
💯+1
